apiVersion : apps/v1
kind: Deployment
metadata:
  name: "82023045" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "82023045"
  template:
    metadata:
      labels:
        app: "82023045" 
    spec:
      containers:
        - name: "82023045"
          image: ceappacr.azurecr.io/82023045
          ports:
          - containerPort: 8080
